version: '2'

services:
  web:
    build: .
    image: qindex/qindex
    container_name: node_container
    volumes:
    - qr4:/app/client/assets/qr
    - basketball1:/app/client/assets/images/basketball
    ports:
    - "3000:3000"
    - "80:3000"
    - "8080:3000"
    links:
    - db
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/QIndex
      NODE_ENV: production
  db:
    image: postgres
    container_name: pg_container
    ports:
    - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: QIndex
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  qr4:
  basketball1: