version: '2'

services:
  db:
    image: postgres
    ports:
    - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: QIndex
  web:
    build: npm install
    command: node .
    image: qindex/qindex
    ports:
    - "3000:3000"
    - "80:3000"
    - "8080:3000"
    links:
    - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/QIndex
      NODE_ENV: production
